# Generated by Django 4.1.7 on 2023-02-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degrees_subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degree',
            options={'verbose_name': 'Classe'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Matière'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AddField(
            model_name='degree',
            name='subject',
            field=models.ManyToManyField(to='degrees_subjects.subject'),
        ),
    ]
