# Generated by Django 4.1.7 on 2023-03-01 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_hour_availablity'),
        ('degrees_subjects', '0002_alter_degree_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDegreeSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='degree',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='teacherdegreesubject',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='degrees_subjects.degree'),
        ),
        migrations.AddField(
            model_name='teacherdegreesubject',
            name='subject',
            field=models.ManyToManyField(to='degrees_subjects.subject'),
        ),
        migrations.AddField(
            model_name='teacherdegreesubject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.teacher'),
        ),
    ]
