# Generated by Django 4.1.7 on 2023-02-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
