# Generated by Django 4.1.7 on 2023-02-21 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('degrees_subjects', '0001_initial'),
        ('account', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='degrees_subjects.degree'),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
