# Generated by Django 4.1.7 on 2023-03-01 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('degrees_subjects', '0003_teacherdegreesubject_remove_degree_subject_and_more'),
        ('account', '0006_hour_availablity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Prix')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degrees_subjects.degree', verbose_name='Classe choisie')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student', verbose_name='Etudiant')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degrees_subjects.subject', verbose_name='Matière choisie')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.teacher', verbose_name='Professeur')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.availablity', verbose_name='Période choisie')),
            ],
        ),
    ]
